### ISSUE TITLE
rozofs-storaged-2.0.~alpha76 /usr/bin/storaged does not create the required directory

### ISSUE THREAD

**Issue by truatpasteurdotfr** [rozofs/rozofs#109]
Hi,

basic config (single partition on a single disk):

/etc/rozofs/storage.conf
```
listen = (
   {
      addr = "*";
      port = 41001;
   }
);


storages = (
  {cid = 1; sid = 2; root = "/sda4"; device-total = 1; device-mapper = 1; device-redundancy = 1;}
);
```

```
$ grep sda4 /proc/mounts 
/dev/sda4 /sda4 xfs rw,relatime,attr2,inode64,noquota 0 0
```

```
$ sudo systemctl start rozofs-storaged
```
does not start the storaged daemon because **/sda4/0** does not exist.

logs:
```
Nov 20 10:09:33 mc-A6.bis.private systemd[1]: Started LSB: RozoFS storaged server.
Nov 20 10:09:33 mc-A6.bis.private storaged[3567]: storage.c - 1162 - severe: can not stat /sda4/0
Nov 20 10:09:33 mc-A6.bis.private storio:1[3569]: storage.c - 1162 - severe: can not stat /sda4/0
Nov 20 10:09:33 mc-A6.bis.private storaged[3567]: storaged_nblock_init.c - 629 - info: storaged non-blocking thread started (dbg port: 50027).
Nov 20 10:09:33 mc-A6.bis.private storio:1[3569]: storio_nblock_init.c - 435 - info: storio started (instance: 1, dbg port: 50028).
Nov 20 10:10:11 mc-A6.bis.private systemd[1]: Stopping LSB: RozoFS storaged server...
```

/sda4 is 755 root:root

Once /sda4/0 created and root:root, perms 755, the daemon happily starts.

**Comment by rozodopamine** [comment]
Hi,
in /etc/rozofs/storage.conf the field root is the root path of your
storage. That is a directory
under which you can mount the RozoFS devices (i.e your disks) of your
RozoFS node.
Your 1rst device must be mounted under <root>/0 your 2nd device under
<root>/1, ...
For each device your have to create the directory <root>/<dev number>. Then
create
an empty file named X under it (when such a file is present RozoFS knows
that the device is
not mounted), and then mount your disk on it.

In your example with only one disk you should set root in the storage
configuration file
to something like "/srv/storage/c1_s2", create /srv/storage/c1_s2/0
directories
and /mnt/storage/c1_s2/0/X empty file
Your fstab should contain:
/dev/sda4 /srv/storage/c1_s2/0 xfs rw,relatime,attr2,inode64,noquota 0 0

Regards,
JPierre



2015-11-20 15:19 GMT+01:00 Tru Huynh <notifications@github.com>:

> Hi,
>
> basic config (single partition on a single disk):
>
> /etc/rozofs/storage.conf
>
> listen = (
>    {
>       addr = "*";
>       port = 41001;
>    }
> );
>
>
> storages = (
>   {cid = 1; sid = 2; root = "/sda4"; device-total = 1; device-mapper = 1; device-redundancy = 1;}
> );
>
> $ grep sda4 /proc/mounts
> /dev/sda4 /sda4 xfs rw,relatime,attr2,inode64,noquota 0 0
>
> $ sudo systemctl start rozofs-storaged
>
> does not start the storaged daemon because */sda4/0* does not exist.
>
> logs:
>
> Nov 20 10:09:33 mc-A6.bis.private systemd[1]: Started LSB: RozoFS storaged server.
> Nov 20 10:09:33 mc-A6.bis.private storaged[3567]: storage.c - 1162 - severe: can not stat /sda4/0
> Nov 20 10:09:33 mc-A6.bis.private storio:1[3569]: storage.c - 1162 - severe: can not stat /sda4/0
> Nov 20 10:09:33 mc-A6.bis.private storaged[3567]: storaged_nblock_init.c - 629 - info: storaged non-blocking thread started (dbg port: 50027).
> Nov 20 10:09:33 mc-A6.bis.private storio:1[3569]: storio_nblock_init.c - 435 - info: storio started (instance: 1, dbg port: 50028).
> Nov 20 10:10:11 mc-A6.bis.private systemd[1]: Stopping LSB: RozoFS storaged server...
>
> /sda4 is 755 root:root
>
> Once /sda4/0 created and root:root, perms 755, the daemon happily starts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/109>.
>



-- 
Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*

**Comment by truatpasteurdotfr** [comment]
thanks, I completely missed that point (storages pointing tot the top level and N for each device).

One more question, if I have 4 storaged nodes, layout=0 and 2 disks on each node.
What is the best practice advice:
  *  2 clusters adressing each 1 disk/storaged sid=1..4
```
{cid = 1; sid = ${sid}; root = "/sda4"; device-total = 1; device-mapper = 1; device-redundancy = 1;},
{cid = 2; sid = ${sid}; root = "/sdb4"; device-total = 1; device-mapper = 1; device-redundancy = 1;}
```
 * 1 cluster and 2 disks/storaged
```
{cid = 1; sid = ${sid}; root = "/sda4"; device-total = 1; device-mapper = 1; device-redundancy = 1;},
{cid = 1; sid = ${sid}; root = "/sdb4"; device-total = 1; device-mapper = 1; device-redundancy = 1;}
```
using -> /sd[ab]4/0
does it make any difference to have
```
{cid = 1; sid = ${sid}; root = "/svr/storage"; device-total = 2; device-mapper = 1; device-redundancy = 1;}
```
and mount /dev/sd[ab]4 under /svr/storage/[01]

**Comment by rozodopamine** [comment]
2015-11-20 16:58 GMT+01:00 Tru Huynh <notifications@github.com>:

> thanks, I completely missed that point (storages pointing tot the top
> level and N for each device).
>
> One more question, if I have 4 storaged nodes, layout=0 and 2 disks on
> each node.
> What is the best practice advice:
>
>    - 2 clusters adressing each 1 disk/storaged sid=1..4
>
> {cid = 1; sid = ${sid}; root = "/sda4"; device-total = 1; device-mapper = 1; device-redundancy = 1;},
> {cid = 2; sid = ${sid}; root = "/sdb4"; device-total = 1; device-mapper = 1; device-redundancy = 1;}
>
>
>    - 1 cluster and 2 disks/storaged
>
> {cid = 1; sid = ${sid}; root = "/sda4"; device-total = 1; device-mapper = 1; device-redundancy = 1;},
> {cid = 1; sid = ${sid}; root = "/sdb4"; device-total = 1; device-mapper = 1; device-redundancy = 1;}
>
> When having 10Gbe interfaces and lots of disks, it is better to make
several clusters since each cluster will be a separate
process to handle the incomming requests. With only few disks, one process
is enough to process the incoming requests
and so one cluster is enough. Do as you like.

1 cluster / 2 disks

storage.conf
{cid = 1; sid = ${sid}; root = "/srv/storage/c1_s${sid}"; device-total = *2*;
device-mapper = *2*; device-redundancy = *2*;}

/etc/fstab
/dev/sda4 /srv/storage/c1_s1/0 xfs rw,relatime,attr2,inode64,noquota 0 0
/dev/sdb4 /srv/storage/c1_s1/1 xfs rw,relatime,attr2,inode64,noquota 0 0

mkdir -p /srv/storage/c1_s${sid}/0
touch  /srv/storage/c1_s${sid}/0/X
mkdir -p /srv/storage/c1_s${sid}/1
touch  /srv/storage/c1_s${sid}/1/X
mount  /srv/storage/c1_s${sid}/0
mount  /srv/storage/c1_s${sid}/1

2 clusters / 1 disk

storage.conf
{cid = 1; sid = ${sid}; root = "/srv/storage/c1_s${sid}"; device-total = *1*;
device-mapper = *1*; device-redundancy = *1*;},
{cid = 2; sid = ${sid}; root = "/srv/storage/c2_s${sid}"; device-total = *1*;
device-mapper = *1*; device-redundancy = *1*;}

/etc/fstab
/dev/sda4 /srv/storage/c1_s1/0 xfs rw,relatime,attr2,inode64,noquota 0 0
/dev/sdb4 /srv/storage/c2_s1/0 xfs rw,relatime,attr2,inode64,noquota 0 0

mkdir -p /srv/storage/c1_s${sid}/0
touch  /srv/storage/c1_s${sid}/0/X
mkdir -p /srv/storage/c2_s${sid}/0
touch  /srv/storage/c2_s${sid}/0/X
mount  /srv/storage/c1_s${sid}/0/X
mount  /srv/storage/c2_s${sid}/0/X

using -> /sd[ab]4/0
> does it make any difference to have
>
> {cid = 1; sid = ${sid}; root = "/svr/storage"; device-total = 2; device-mapper = 1; device-redundancy = 1;}
>
> and mount /dev/sd[ab]4 under /svr/storage/[01]
>
I do not understand what you mean. Can you precise the question ?
Regards,
JPierre

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/109#issuecomment-158441135>.
>



-- 
Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*

**Comment by truatpasteurdotfr** [comment]
I was wondering it 1 cluster/2 disks could be achived by different solutions:
```
 storage.conf
 {cid = 1; sid = ${sid}; root = "/srv/storage/c1_s${sid}"; device-total = *2*; device-mapper = *2*; device-redundancy = *2*;}

 /etc/fstab:
 /dev/sda4 /srv/storage/c1_s1/0 xfs rw,relatime,attr2,inode64,noquota 0 0
 /dev/sdb4 /srv/storage/c1_s1/1 xfs rw,relatime,attr2,inode64,noquota 0 0 
```

or
```
 storage.conf
 {cid = 1; sid = ${sid}; root = "/srv/storage/c1_s${sid}-sda"; device-total = 1; device-mapper = 1; device-redundancy = 1;},
 {cid = 1; sid = ${sid}; root = "/srv/storage/c1_s${sid}-sdb"; device-total = 1; device-mapper = 1; device-redundancy = 1;}
 /etc/fstab
/dev/sda4 /srv/storage/c1_s1-sda/0 xfs rw,relatime,attr2,inode64,noquota 0 0 
/dev/sdb4 /srv/storage/c1_s1-sdb/0 xfs rw,relatime,attr2,inode64,noquota 0 0 
```
I am probably confused!

Thanks for your valued feedback, much appreciated.

**Comment by rozodopamine** [comment]
Proposal 2 is not valid for RozoFS. You can only define one time a cid/sid
tupple
in sorage.conf. So one cid/sid has only one root path under which are
mounted as
many disks as you like.

2015-11-20 23:00 GMT+01:00 Tru Huynh <notifications@github.com>:

> I was wondering it 1 cluster/2 disks could be achived by different
> solutions:
>
>  storage.conf
>  {cid = 1; sid = ${sid}; root = "/srv/storage/c1_s${sid}"; device-total = *2*; device-mapper = *2*; device-redundancy = *2*;}
>
>  /etc/fstab:
>  /dev/sda4 /srv/storage/c1_s1/0 xfs rw,relatime,attr2,inode64,noquota 0 0
>  /dev/sdb4 /srv/storage/c1_s1/1 xfs rw,relatime,attr2,inode64,noquota 0 0
>
> or
>
>  storage.conf
>  {cid = 1; sid = ${sid}; root = "/srv/storage/c1_s${sid}-sda"; device-total = 1; device-mapper = 1; device-redundancy = 1;},
>  {cid = 1; sid = ${sid}; root = "/srv/storage/c1_s${sid}-sdb"; device-total = 1; device-mapper = 1; device-redundancy = 1;}
>  /etc/fstab
> /dev/sda4 /srv/storage/c1_s1-sda/0 xfs rw,relatime,attr2,inode64,noquota 0 0
> /dev/sdb4 /srv/storage/c1_s1-sdb/0 xfs rw,relatime,attr2,inode64,noquota 0 0
>
> I am probably confused!
>
> Thanks for your valued feedback, much appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/109#issuecomment-158537591>.
>



-- 
Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*

**Comment by truatpasteurdotfr** [comment]
fair enough :D thx
