### ISSUE TITLE
the xml problem

### ISSUE THREAD

**Issue by cchb1990** [rozofs/rozofs#115]
I follow the guide to install rozofs with centos7 + pcs + corosync + pacemaker, but I get the following problem. who can help me to solve it
Jan 16 05:49:21 master2 crmd[3230]: error: pcmkRegisterNode: Triggered assert at xml.c:594 : node->type == XML_ELEMENT_NODE
Jan 16 05:49:21 master2 attrd[3228]: notice: Updating all attributes after cib_refresh_notify event
Jan 16 05:49:21 master2 stonith-ng[3226]: notice: Versions did not change in patch 0.33.103
Jan 16 05:49:21 master2 crmd[3230]: error: Failed to retrieve meta-data for ocf:heartbeat:exportd
Jan 16 05:49:21 master2 crmd[3230]: warning: No metadata found for exportd::ocf:heartbeat: Input/output error (-5)
Jan 16 05:49:21 master2 crmd[3230]: error: No metadata for heartbeat::ocf:exportd

**Comment by rozoadrenaline** [comment]
It seems that exportd OCF resource agent is not installed. This resource agent is available [here](https://github.com/rozofs/rozofs/blob/master/contrib/heartbeat/exportd).
