### ISSUE TITLE
high load average caused by 4x D state storcli and rozofsmount threads 

### ISSUE THREAD

**Issue by truatpasteurdotfr** [rozofs/rozofs#117]
Hi,

installed:
rozofs-rozolauncher-2.0.~alpha90-1.el6.x86_64
rozofs-manager-agent-2.0.~alpha90-1.el6.x86_64
repo-rozofs-mdevice-1.0-1.el6.noarch
rozofs-manager-cli-2.0.~alpha90-1.el6.x86_64
rozofs-rozofsmount-2.0.~alpha90-1.el6.x86_64
rozofs-manager-lib-2.0.~alpha90-1.el6.x86_64

running CentOS-6.7 x86_64 (2.6.32-573.18.1.el6.x86_64) test bed (single core with 16 GB of RAM)

1. clean boot and just installed the rozofs client
2.  sudo rozofsmount -H tlalac.erc -E /rozofs/one /mnt/rozofs

load jumps from 0 to 4 without any work on the client. Is there anything I can do?

top ouput (threads  listing enabled) show 4 "D" processes.
[b.txt](https://github.com/rozofs/rozofs/files/132705/b.txt)

**Comment by truatpasteurdotfr** [comment]
[tru@c-esxi ~]$  rozo node status -E tlalac.erc
c006.erc:
- STORAGED: running
tlalac.erc:
- EXPORTD: running
c003.erc:
- STORAGED: running
c001.erc:
- STORAGED: running
c007.erc:
- STORAGED: running
c005.erc:
- STORAGED: running
c004.erc:
- STORAGED: running
c002.erc:
- STORAGED: running
c008.erc:
- STORAGED: running
[tru@c-esxi ~]$  rozo node config -E tlalac.erc
'NODE: c007.erc':
- STORAGED:
  - OPTIONS:
    - crc32c_check: false
    - crc32c_generate: false
    - crc32c_hw_forced: false
  - INTERFACE:
    - '*': 41001
  - STORAGE:
    - cid 1, sid 7:
        root: /srv/storage/c1_s7
        device-total: 1
        device-mapper: 1
        device-redundancy: 1
'NODE: c006.erc':
- STORAGED:
  - OPTIONS:
    - crc32c_check: false
    - crc32c_generate: false
    - crc32c_hw_forced: false
  - INTERFACE:
    - '*': 41001
  - STORAGE:
    - cid 1, sid 6:
        root: /srv/storage/c1_s6
        device-total: 1
        device-mapper: 1
        device-redundancy: 1
'NODE: c005.erc':
- STORAGED:
  - OPTIONS:
    - crc32c_check: false
    - crc32c_generate: false
    - crc32c_hw_forced: false
  - INTERFACE:
    - '*': 41001
  - STORAGE:
    - cid 1, sid 5:
        root: /srv/storage/c1_s5
        device-total: 1
        device-mapper: 1
        device-redundancy: 1
'NODE: tlalac.erc':
- EXPORTD:
  - VOLUME:
    - volume 1:
      - cluster 1:
        - sid 1: c001.erc
        - sid 2: c002.erc
        - sid 3: c003.erc
        - sid 4: c004.erc
        - sid 5: c005.erc
        - sid 6: c006.erc
        - sid 7: c007.erc
        - sid 8: c008.erc
  - EXPORT:
      vid: 1
      root: /rozofs/one
      md5: ''
      squota: ''
      hquota: ''
'NODE: c004.erc':
- STORAGED:
  - OPTIONS:
    - crc32c_check: false
    - crc32c_generate: false
    - crc32c_hw_forced: false
  - INTERFACE:
    - '*': 41001
  - STORAGE:
    - cid 1, sid 4:
        root: /srv/storage/c1_s4
        device-total: 1
        device-mapper: 1
        device-redundancy: 1
'NODE: c003.erc':
- STORAGED:
  - OPTIONS:
    - crc32c_check: false
    - crc32c_generate: false
    - crc32c_hw_forced: false
  - INTERFACE:
    - '*': 41001
  - STORAGE:
    - cid 1, sid 3:
        root: /srv/storage/c1_s3
        device-total: 1
        device-mapper: 1
        device-redundancy: 1
'NODE: c002.erc':
- STORAGED:
  - OPTIONS:
    - crc32c_check: false
    - crc32c_generate: false
    - crc32c_hw_forced: false
  - INTERFACE:
    - '*': 41001
  - STORAGE:
    - cid 1, sid 2:
        root: /srv/storage/c1_s2
        device-total: 1
        device-mapper: 1
        device-redundancy: 1
'NODE: c001.erc':
- STORAGED:
  - OPTIONS:
    - crc32c_check: false
    - crc32c_generate: false
    - crc32c_hw_forced: false
  - INTERFACE:
    - '*': 41001
  - STORAGE:
    - cid 1, sid 1:
        root: /srv/storage/c1_s1
        device-total: 1
        device-mapper: 1
        device-redundancy: 1
'NODE: c008.erc':
- STORAGED:
  - OPTIONS:
    - crc32c_check: false
    - crc32c_generate: false
    - crc32c_hw_forced: false
  - INTERFACE:
    - '*': 41001
  - STORAGE:
    - cid 1, sid 8:
        root: /srv/storage/c1_s8
        device-total: 1
        device-mapper: 1
        device-redundancy: 1

**Comment by rozonicotine** [comment]
Hello,

The issue is not related to rozoFS but to linux. It happens when a system
is using AF_UNIX and when more than one thread are waiting on the queue. It
is just a stats issue that does not exist anymore in Centos 7 and is not
seen either on debian.

Best Regards,

Didier Féron

2016-02-16 15:58 GMT+01:00 Tru Huynh <notifications@github.com>:

> Hi,
>
> installed:
> rozofs-rozolauncher-2.0.~alpha90-1.el6.x86_64
> rozofs-manager-agent-2.0.~alpha90-1.el6.x86_64
> repo-rozofs-mdevice-1.0-1.el6.noarch
> rozofs-manager-cli-2.0.~alpha90-1.el6.x86_64
> rozofs-rozofsmount-2.0.~alpha90-1.el6.x86_64
> rozofs-manager-lib-2.0.~alpha90-1.el6.x86_64
>
> running CentOS-6.7 x86_64 (2.6.32-573.18.1.el6.x86_64) test bed (single
> core with 16 GB of RAM)
>
>    1. clean boot and just installed the rozofs client
>    2. sudo rozofsmount -H tlalac.erc -E /rozofs/one /mnt/rozofs
>
> load jumps from 0 to 4 without any work on the client. Is there anything I
> can do?
>
> top ouput (threads listing enabled) show 4 "D" processes.
> b.txt <https://github.com/rozofs/rozofs/files/132705/b.txt>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/117>.
>



-- 
Didier FERON
CTO

+33.2.51.85.74.21
+33.6.47.93.08.95
didier.feron@rozofs.com <didier.feron@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs

**Comment by truatpasteurdotfr** [comment]
Thanks,  is there a way to reduce the number of threads waiting in the queue?

**Comment by rozodopamine** [comment]
This is a centos bug.
