### ISSUE TITLE
what is the proper way to reduce the size of a volume?

### ISSUE THREAD

**Issue by truatpasteurdotfr** [rozofs/rozofs#118]
Before I burn myself, by expanding the volume by adding another cluster?

[tru@c-esxi ~]$ rozo volume list -E tlalac.erc
EXPORTD on tlalac.erc:
- VOLUME 1:
  - LAYOUT: 1
  - CLUSTER 1:
    - STORAGE 1: c001.erc
    - STORAGE 2: c002.erc
    - STORAGE 3: c003.erc
    - STORAGE 4: c004.erc
    - STORAGE 5: c005.erc
    - STORAGE 6: c006.erc
    - STORAGE 7: c007.erc
    - STORAGE 8: c008.erc

I presume I can add a second cluster to the volume 1 with:

$ rozo volume expand -v 1 c009.erc c010.erc c011.erc c012.erc c013.erc c014.erc c015.erc c016.erc -E tlalac.erc

Then how do I revert or remove cluster1 or cluster2 from volume 1?

Thanks

**Comment by rozoadrenaline** [comment]
At the moment, It's not possible to remove one specific cluster from one volume, only the deleting of entire volume is possible.
Regards.

**Comment by truatpasteurdotfr** [comment]
thanks. I am looking forward for this enhancement!
