### ISSUE TITLE
Issue while building rozofs in ubuntu docker container

### ISSUE THREAD

**Issue by aniruddh-a** [rozofs/rozofs#119]
I am exploring rozofs. While installing inside ubuntu docker container, I am getting following error and can't proceed to install. Any help is appreciated. 
Please find more details below :

Phase : build 
step : make 
packages installed for dependencies  : 
apt-get install -y gcc make cmake libfuse-dev libattr1-dev uuid-dev libconfig-dev libreadline-dev pyro python2.7-dev python-yaml rpcbind swig libssl

environment :
GNU Make 3.81
Linux cd1d80d162bb 3.19.0-49-generic 55~14.04.1-Ubuntu SMP Fri Jan 22 11:24:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Error message:
```
/home/rozofs/rozofs/rozofs/core/rozofs_ip_utilities.h: In function 'rozofs_host2ip':
/home/rozofs/rozofs/rozofs/core/rozofs_ip_utilities.h:57:3: warning: incompatible implicit declaration of built-in function 'bcopy' [enabled by default]
   bcopy((char *) hp->h_addr, (char *) ipaddr_p, hp->h_length);
   ^
/home/rozofs/rozofs/rozofs/core/rozofs_ip_utilities.h:57:20: error: 'struct hostent' has no member named 'h_addr'
   bcopy((char *) hp->h_addr, (char *) ipaddr_p, hp->h_length);

```

**Comment by rozonicotine** [comment]
Hello,

RozoFS is compiling for Centos, Debian and Ubuntu targets. So it should be
ok.

It looks like that you attempt to build RozoFS from source code. What is
the branch that you are using?
The branch to use for RozoFS is feature/mdevice.

The issue that you are facing is related to some data structure in
<netdb.h>.:

/* Description of data base entry for a single host.  */
struct hostent
{
  char *h_name; /* Official name of host.  */
  char **h_aliases; /* Alias list.  */
  int h_addrtype; /* Host address type.  */
  int h_length; /* Length of address.  */
  char **h_addr_list; /* List of addresses from name server.  */
#if defined __USE_MISC || defined __USE_GNU
# define h_addr h_addr_list[0] /* Address, for backward compatibility.*/
#endif
};

If for any reason __USE_GNU is not asserted, you will face that compilation
issue.

Have follow the build procedure that you can  find  in
https://github.com/rozofs/rozofs (REAME.md) ?

Best Regards

Didier

2016-03-08 10:29 GMT+01:00 Aniruddh Adkar <notifications@github.com>:

> I am exploring rozofs. While installing inside ubuntu docker container, I
> am getting following error and can't proceed to install. Any help is
> appreciated.
> Please find more details below :
>
> Phase : build
> step : make
> packages installed for dependencies :
> apt-get install -y gcc make cmake libfuse-dev libattr1-dev uuid-dev
> libconfig-dev libreadline-dev pyro python2.7-dev python-yaml rpcbind swig
> libssl
>
> environment :
> GNU Make 3.81
> Linux cd1d80d162bb 3.19.0-49-generic 55~14.04.1-Ubuntu SMP Fri Jan 22
> 11:24:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
>
> Error message:
>
> /home/rozofs/rozofs/rozofs/core/rozofs_ip_utilities.h: In function 'rozofs_host2ip':
> /home/rozofs/rozofs/rozofs/core/rozofs_ip_utilities.h:57:3: warning: incompatible implicit declaration of built-in function 'bcopy' [enabled by default]
>    bcopy((char *) hp->h_addr, (char *) ipaddr_p, hp->h_length);
>    ^
> /home/rozofs/rozofs/rozofs/core/rozofs_ip_utilities.h:57:20: error: 'struct hostent' has no member named 'h_addr'
>    bcopy((char *) hp->h_addr, (char *) ipaddr_p, hp->h_length);
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/119>.
>



-- 
Didier FERON
CTO

+33.2.51.85.74.21
+33.6.47.93.08.95
didier.feron@rozofs.com <didier.feron@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs
