### ISSUE TITLE
copy on write/ snapshot

### ISSUE THREAD

**Issue by ptulpen** [rozofs/rozofs#125]
hello, this is less a issue than more a general question: 
dos rozofs have a copy on write functionality or something similar?
we often have files or folder which are copied for testing, but then only a few chuncks are changed

(If this is not the case, are there any experiences with sambas server-side copy functionality in combination with rozo?)
Best regards,
Marius

**Comment by rozodopamine** [comment]
Hi Marius,
RozoFS has no COW system and does not have snapshots.
Nevertheless I do not understand your point. When you make a copy of a file
or directory
you get two times the initial data with or without COW If you then just
change few chunks
only these few chunks are re-written with RozoFS, while with COW you will
have to allocate
more space to store the modified chunks...
We provide the ability to have server side copy on a SAMBA server when the
origin and
destination are on the same share.
Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2016-08-04 15:04 GMT+02:00 ptulpen <notifications@github.com>:

**Comment by ptulpen** [comment]
Hello,
well my idea of copy on write was, that only these few chunks are re-written, so I dont see how COW will allocate more space? (I am note sure yet where I mixed it up)

And is there anything specific to let SAMBA use server side copy with rozo or is it the normal samba funtion?

**Comment by rozodopamine** [comment]
Hello,
the server side copy is supported by SAMBA as long as the origin and
destination are on the same share.
If the origin and destination are on different shares you need a patch in
the SAMBA server.
You of course also need your client side to support such a feature.
Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2016-08-08 15:53 GMT+02:00 ptulpen <notifications@github.com>:

**Comment by rozonicotine** [comment]
See last answer
