### ISSUE TITLE
check_rozofs_storaged.sh broken when no space around profiler values

### ISSUE THREAD

**Issue by jmichalon** [rozofs/rozofs#126]
Hello,

It seems that the storaged check script is broken if no space is laid around the pipes on profiler write output (read would be the same I suppose).
```
./check_rozofs_storaged.sh -H localhost
./check_rozofs_storaged.sh: line 176: |: syntax error: operand expected (error token is "|")
```

```
/usr/bin/rozodiag -i localhost -T storio:1 -c profiler
 write            |    142711298 |         2785 |          359 |9784920670144 |              182 |
```

If I force some spaces around the pipe at line 164, it works.
`  $ROZDBG -c profiler | sed 's/|/ | /g' >  $TMPFILE`

This is a small issue, dunno if the hack is the best way to workaround, or if it would be better to ensure spaces are placed in the actual rozodiag output.

**Comment by rozodopamine** [comment]
Spaces have been added in 2.0.12 release.
