### ISSUE TITLE
Duplicate entries of dirs and files

### ISSUE THREAD

**Issue by lwandrebeck** [rozofs/rozofs#128]
Hi,

Centos 7, 2.0.10 (btw, 2.0.11 and 2.0.12 have not been build in repo, it seems), layout 1.

While running the following:

wget --load-cookies ~/.urs_cookies --save-cookies ~/.urs_cookies --auth-no-challenge=on --keep-session-cookies -i wget_dJFjbRKR

.urs_cookies being:
# HTTP cookie file.
# Generated by Wget on 2016-08-19 12:24:47.
# Edit at your own risk.

urs.earthdata.nasa.gov	FALSE	/	FALSE	1471688687	_urs-gui_session	Y2N6QTZXY0U3cUc5dFdFMGJSSFdZNmtzMHpnU2V2MzdvU3c0Q0FxZGZFQnRieDhYQWJzUVdIQU5KNStJVllrSVB6TlB4YlA4S0g5b1d1S2QvM1lJekxzRy8xYUNQRndRY291QzhMYnRJc3F4ZjlZV0s1MTNpUHVJTlROZTN4SDMtLWdsS1JMTHNWZHIrdlUwVFNCWUlZb2c9PQ%3D%3D--c2d9a3e15c1bafe374ea24007ec46cdbc99b6828
.earthdata.nasa.gov	TRUE	/	FALSE	1471688687	urs_user_already_logged	yes

a couple lines of of wget_dJFjbRKR being (and so on) : 
http://goldsmr4.gesdisc.eosdis.nasa.gov/daac-bin/OTF/HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2002%2F01%2FMERRA2_300.inst1_2d_int_Nx.20020101.nc4&FORMAT=bmM0Lw&BBOX=-90%2C-180%2C90%2C180&TIME=1979-01-01T00%3A00%3A00%2F1979-01-01T23%3A00%3A00&LABEL=MERRA2_300.inst1_2d_int_Nx.20020101.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv
http://goldsmr4.gesdisc.eosdis.nasa.gov/daac-bin/OTF/HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2002%2F01%2FMERRA2_300.inst1_2d_int_Nx.20020102.nc4&FORMAT=bmM0Lw&BBOX=-90%2C-180%2C90%2C180&TIME=1979-01-01T00%3A00%3A00%2F1979-01-01T23%3A00%3A00&LABEL=MERRA2_300.inst1_2d_int_Nx.20020102.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv
http://goldsmr4.gesdisc.eosdis.nasa.gov/daac-bin/OTF/HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2002%2F01%2FMERRA2_300.inst1_2d_int_Nx.20020103.nc4&FORMAT=bmM0Lw&BBOX=-90%2C-180%2C90%2C180&TIME=1979-01-01T00%3A00%3A00%2F1979-01-01T23%3A00%3A00&LABEL=MERRA2_300.inst1_2d_int_Nx.20020103.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv

it resulted in (after trying to delete 2011 directory due to multiple entries) via ls -i :

ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
ls: cannot access 2011: No such file or directory
2010294283667505184 2002
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
                  ? 2011
1461699554058439968 HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2002%2F01%2FMERRA2_300.inst1_2d_int_Nx.20020101.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_300.inst1_2d_int_Nx.20020101.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv
1461981029035150624 HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2002%2F01%2FMERRA2_300.inst1_2d_int_Nx.20020102.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_300.inst1_2d_int_Nx.20020102.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv

<snip>

1440870405781851936 HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2012%2F12%2FMERRA2_400.inst1_2d_int_Nx.20121230.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_400.inst1_2d_int_Nx.20121230.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv
1441151880758562592 HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2012%2F12%2FMERRA2_400.inst1_2d_int_Nx.20121231.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_400.inst1_2d_int_Nx.20121231.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR
1358961187559050528 wget_dJFjbRKR

After unmounting and remounting on client, same content. I can’t for now get FS status back to normal.
What do you need to track that bug down ?

Thanks

**Comment by rozoadrenaline** [comment]
About packaging:
New packages are now available in the repository.

About the bug:
Could you send us the syslog file of your exportd node ?

Thanks

**Comment by lwandrebeck** [comment]
I’m seeing lots of : 
août 19 11:24:12 master1.****.*** export_slave_1[3016162]: dirent_file.c - 1170 - severe: put_mdirentry at line 1170
août 19 11:24:12 master1.****.*** export_slave_1[3016162]: mdirent.h - 2702 - severe: dirent_create_entry_name: out of chunk error at line 2702

Other than that, nothing particular.

**Comment by rozodopamine** [comment]
Hi,
hotcode 2.0.13 should fix the problem.
Best regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2016-08-19 14:44 GMT+02:00 Laurent Wandrebeck <notifications@github.com>:

**Comment by lwandrebeck** [comment]
Hi Jean-Pierre,

Restarted exportd, umount/mount of rfs on a client, it looks very well like the fix is fine, things are back to normal state :+1: 

Thanks a lot,
Keep up the good work !

**Comment by lwandrebeck** [comment]
Hmmmm. User have launched the same script in another dir before the fix was installed, and that dir remains broken.

ls: cannot access HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2004%2F01%2FMERRA2_300.inst1_2d_int_Nx.20040119.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_300.inst1_2d_int_Nx.20040119.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv: No such file or directory
HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2004%2F01%2FMERRA2_300.inst1_2d_int_Nx.20040119.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_300.inst1_2d_int_Nx.20040119.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv

**Comment by rozodopamine** [comment]
Can you please re run the ls and provide me with the complete traces of the
ls as well as the syslog when the ls is run.
Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2016-08-23 10:56 GMT+02:00 Laurent Wandrebeck <notifications@github.com>:

**Comment by lwandrebeck** [comment]
Silly me, should have taken a look at it before posting…

août 23 11:05:21 master1.hygeos.com export_slave_1[3310947]: mdirent.h - 2614 - severe: dirent_get_entry_name_ptr at line 2614
août 23 11:05:21 master1.hygeos.com export_slave_1[3310947]: dirent_search.c - 310 - severe: dirent_cache_search_hash_entry: pointer does not exist at line 310

**Comment by rozodopamine** [comment]
Fix was not complete. Please try 2.0.14
Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2016-08-23 11:06 GMT+02:00 Laurent Wandrebeck <notifications@github.com>:

**Comment by lwandrebeck** [comment]
update to 2.0.14, exportd restarted.

[root@planchet ~]# ls /rfs/data/MERRA2/tpwv/ -l
total 37
-rw-r--r--. 1 mathieu users 37257 19 août  11:26 HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2004%2F01%2FMERRA2_300.inst1_2d_int_Nx.20040119.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_300.inst1_2d_int_Nx.20040119.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv
[root@planchet ~]# cd /rfs/data/MERRA2/
[root@planchet MERRA2]# rm -rf tpwv/
rm: impossible de supprimer « tpwv/ »: Le dossier n'est pas vide
[root@planchet MERRA2]# ls tpwv/
HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2004%2F01%2FMERRA2_300.inst1_2d_int_Nx.20040119.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_300.inst1_2d_int_Nx.20040119.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv
[root@planchet MERRA2]# cd tpwv/
[root@planchet tpwv]# ll
total 37
-rw-r--r--. 1 mathieu users 37257 19 août  11:26 HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2004%2F01%2FMERRA2_300.inst1_2d_int_Nx.20040119.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_300.inst1_2d_int_Nx.20040119.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv
[root@planchet tpwv]# rm HTTP_services.cgi\?FILENAME\=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2004%2F01%2FMERRA2_300.inst1_2d_int_Nx.20040119.nc4\&FORMAT\=bmM0Lw\&BBOX\=-90\,-180\,90\,180\&TIME\=1979-01-01T00\:00\:00%2F1979-01-01T23\:00\:00\&LABEL\=MERRA2_300.inst1_2d_int_Nx.20040119.SUB.nc4\&FLAGS\=\&SHORTNAME\=M2I1NXINT\&SERVICE\=SUBSET_MERRA2\&LAYERS\=\&VERSION\=1.02\&VARIABLES\=tqv 
rm : supprimer fichier « HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2004%2F01%2FMERRA2_300.inst1_2d_int_Nx.20040119.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_300.inst1_2d_int_Nx.20040119.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv » ? o
[root@planchet tpwv]# ls
HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2004%2F01%2FMERRA2_300.inst1_2d_int_Nx.20040119.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_300.inst1_2d_int_Nx.20040119.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv
[root@planchet tpwv]# cd
[root@planchet ~]# umount /rfs
[root@planchet ~]# mount /rfs
[root@planchet ~]# cd /rfs/data/MERRA2/tpwv/
[root@planchet tpwv]# ll
total 37
-rw-r--r--. 1 mathieu users 37257 19 août  11:26 HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2004%2F01%2FMERRA2_300.inst1_2d_int_Nx.20040119.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_300.inst1_2d_int_Nx.20040119.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv
[root@planchet tpwv]# rm -f HTTP_services.cgi\?FILENAME\=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2004%2F01%2FMERRA2_300.inst1_2d_int_Nx.20040119.nc4\&FORMAT\=bmM0Lw\&BBOX\=-90\,-180\,90\,180\&TIME\=1979-01-01T00\:00\:00%2F1979-01-01T23\:00\:00\&LABEL\=MERRA2_300.inst1_2d_int_Nx.20040119.SUB.nc4\&FLAGS\=\&SHORTNAME\=M2I1NXINT\&SERVICE\=SUBSET_MERRA2\&LAYERS\=\&VERSION\=1.02\&VARIABLES\=tqv 
[root@planchet tpwv]# ls
HTTP_services.cgi?FILENAME=%2Fdata%2FMERRA2%2FM2I1NXINT.5.12.4%2F2004%2F01%2FMERRA2_300.inst1_2d_int_Nx.20040119.nc4&FORMAT=bmM0Lw&BBOX=-90,-180,90,180&TIME=1979-01-01T00:00:00%2F1979-01-01T23:00:00&LABEL=MERRA2_300.inst1_2d_int_Nx.20040119.SUB.nc4&FLAGS=&SHORTNAME=M2I1NXINT&SERVICE=SUBSET_MERRA2&LAYERS=&VERSION=1.02&VARIABLES=tqv
[root@planchet tpwv]# cd ..
[root@planchet MERRA2]# rm -f tpwv/
rm: impossible de supprimer « tpwv/ »: est un dossier
[root@planchet MERRA2]# rm -rf tpwv/
rm: impossible de supprimer « tpwv/ »: Le dossier n'est pas vide

**Comment by rozodopamine** [comment]
Please try this to cleanup the directory:

attr -s rozofs -V "children = 0"  /rfs/data/MERRA2/tpwv/
rmdir /rfs/data/MERRA2/tpwv/

Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2016-08-23 15:03 GMT+02:00 Laurent Wandrebeck <notifications@github.com>:

**Comment by lwandrebeck** [comment]
That did the trick, thanks a lot Jean-Pierre ! :)
