### ISSUE TITLE
check_rozofs_volume.sh broken when crm reports failure

### ISSUE THREAD

**Issue by jmichalon** [rozofs/rozofs#129]
When using _check_rozofs_volume.sh_ and _rozodiag  -T export -c synchro crm_ reports failure, the check is broken.
At lines 311 and 312 it should probably read something like :

```
  DETAILS=`cat $SYNCHRO | awk '/Failed/ { f=1 }f' | grep --invert-match Failed`
  COUNT=`cat $SYNCHRO | awk '/Failed/ { f=1 }f' | grep --invert-match --count Failed`
```

Maybe not the best fix but at least it works for me like that :)

**Comment by rozodopamine** [comment]
Fixed in master
