### ISSUE TITLE
Provide additional tools for monitoring

### ISSUE THREAD

**Issue by lbeltrame** [rozofs/rozofs#130]
I've found myself in the need for monitoring I/O throughput in RozoFS and at least according to the docs, there is no clear way to do so. I noticed that `storio` has, through `rozodiag` an option to misure throughput, but 

```
rozodiag -i hibari -T storio:0 -c th
____[storio1]__[th ]____
throughput measurement is disabled
```

I think tools to extract these information (a la `iostat` or `nfsiostat`) would be very helpful for monitoring real-world scenarios.

**Comment by rozodopamine** [comment]
Hi Luca,
the throughput measures must be enabled on the storio
rozodiag -i localhost1 -T storio:1
_________________________________________________________
[192.168.10.1:50028] storio1 192.168.10.1> thr
____[storio1 192.168.10.1]__[thr]____
throughput measurement is disabled
_________________________________________________________
[192.168.10.1:50028] storio1 192.168.10.1> throughput ?
____[storio1 192.168.10.1]__[throughput ?]____

unexpected parameter
throughput [enable|disable|read|write|col <#col>|avg]
_________________________________________________________
[192.168.10.1:50028] storio1 192.168.10.1> thr enable
____[storio1 192.168.10.1]__[thr enable]____
throughput measurement enabled
_________________________________________________________
[192.168.10.1:50028] storio1 192.168.10.1> throughput col 5
____[storio1 192.168.10.1]__[throughput col 5]____
 _____ _________ _________  _____ _________ _________  _____ _________
_________  _____ _________ _________  _____ _________ _________
| T.S | Read    | Write   || T.S | Read    | Write   || T.S | Read    |
Write   || T.S | Read    | Write   || T.S | Read    | Write   |
|_____|_________|_________||_____|_________|_________||_____|_________|_________||_____|_________|_________||_____|_________|_________|
|  -1 |    0  B |    0  B || -13 |    0  B |    0  B || -25 |    0  B |
 0  B || -37 |    0  B |    0  B || -49 |    0  B |    0  B |
|  -2 |    0  B |    0  B || -14 |    0  B |    0  B || -26 |    0  B |
 0  B || -38 |    0  B |    0  B || -50 |    0  B |    0  B |
|  -3 |    0  B |    0  B || -15 |    0  B |    0  B || -27 |    0  B |
 0  B || -39 |    0  B |    0  B || -51 |    0  B |    0  B |
|  -4 |    0  B |    0  B || -16 |    0  B |    0  B || -28 |    0  B |
 0  B || -40 |    0  B |    0  B || -52 |    0  B |    0  B |
|  -5 |    0  B |    0  B || -17 |    0  B |    0  B || -29 |    0  B |
 0  B || -41 |    0  B |    0  B || -53 |    0  B |    0  B |
|  -6 |    0  B |    0  B || -18 |    0  B |    0  B || -30 |    0  B |
 0  B || -42 |    0  B |    0  B || -54 |    0  B |    0  B |
|  -7 |    0  B |    0  B || -19 |    0  B |    0  B || -31 |    0  B |
 0  B || -43 |    0  B |    0  B || -55 |    0  B |    0  B |
|  -8 |    0  B |    0  B || -20 |    0  B |    0  B || -32 |    0  B |
 0  B || -44 |    0  B |    0  B || -56 |    0  B |    0  B |
|  -9 |    0  B |    0  B || -21 |    0  B |    0  B || -33 |    0  B |
 0  B || -45 |    0  B |    0  B || -57 |    0  B |    0  B |
| -10 |    0  B |    0  B || -22 |    0  B |    0  B || -34 |    0  B |
 0  B || -46 |    0  B |    0  B || -58 |    0  B |    0  B |
| -11 |    0  B |    0  B || -23 |    0  B |    0  B || -35 |    0  B |
 0  B || -47 |    0  B |    0  B || -59 |    0  B |    0  B |
| -12 |    0  B |    0  B || -24 |    0  B |    0  B || -36 |    0  B |
 0  B || -48 |    0  B |    0  B || -60 |    0  B |    0  B |
|_____|_________|_________||_____|_________|_________||_____|_________|_________||_____|_________|_________||_____|_________|_________|

Here is displayed the throughput in Read and Write of the last second (-1),
and the second before (-2), up to one minute before (-60)
Nevertheless this one shows the throughput of one storio. You may prefer
getting the throughput on every mountpoint.
rozodiag -T mount:0
_________________________________________________________
[127.0.0.1:50003] rozofsmount 0> thr col 6
____[rozofsmount 0]__[thr col 6]____
 _____ _________ _________  _____ _________ _________  _____ _________
_________  _____ _________ _________  _____ _________ _________  _____
_________ _________
| T.S | Read    | Write   || T.S | Read    | Write   || T.S | Read    |
Write   || T.S | Read    | Write   || T.S | Read    | Write   || T.S | Read
   | Write   |
|_____|_________|_________||_____|_________|_________||_____|_________|_________||_____|_________|_________||_____|_________|_________||_____|_________|_________|
|  -1 |    0  B |    0  B || -11 |    0  B |    0  B || -21 | 16.5 MB |
 0  B || -31 | 16.7 MB | 74.4 MB || -41 |    0  B |    0  B || -51 |    0
 B |    0  B |
|  -2 |    0  B |    0  B || -12 |    0  B |    0  B || -22 | 37.2 MB |
59.7 MB || -32 | 88.0 MB | 28.3 MB || -42 |    0  B |    0  B || -52 |    0
 B |    0  B |
|  -3 |    0  B |    0  B || -13 |    0  B |    0  B || -23 | 55.8 MB |
45.0 MB || -33 | 11.7 MB | 76.5 MB || -43 |    0  B |    0  B || -53 |    0
 B |    0  B |
|  -4 |    0  B |    0  B || -14 |    0  B |    0  B || -24 | 49.0 MB |
54.7 MB || -34 | 93.0 MB | 21.2 MB || -44 |    0  B |    0  B || -54 |    0
 B |    0  B |
|  -5 |    0  B |    0  B || -15 |    0  B |    0  B || -25 | 45.8 MB |
50.0 MB || -35 |    0  B | 83.6 MB || -45 |    0  B |    0  B || -55 |    0
 B |    0  B |
|  -6 |    0  B |    0  B || -16 |    0  B |    0  B || -26 | 58.9 MB |
43.2 MB || -36 |    0  B |    0  B || -46 |    0  B |    0  B || -56 |    0
 B |    0  B |
|  -7 |    0  B |    0  B || -17 |    0  B |    0  B || -27 | 33.0 MB |
61.6 MB || -37 |    0  B |    0  B || -47 |    0  B |    0  B || -57 |    0
 B |    0  B |
|  -8 |    0  B |    0  B || -18 |    0  B |    0  B || -28 | 71.8 MB |
33.5 MB || -38 |    0  B |    0  B || -48 |    0  B |    0  B || -58 |    0
 B |    0  B |
|  -9 |    0  B |    0  B || -19 |    0  B |    0  B || -29 | 18.6 MB |
71.3 MB || -39 |    0  B |    0  B || -49 |    0  B |    0  B || -59 |    0
 B |    0  B |
| -10 |    0  B |    0  B || -20 |    0  B |    0  B || -30 | 86.2 MB |
30.4 MB || -40 |    0  B |    0  B || -50 |    0  B |    0  B || -60 |    0
 B |    0  B |
|_____|_________|_________||_____|_________|_________||_____|_________|_________||_____|_________|_________||_____|_________|_________||_____|_________|_________|
You need not to enable/disable the throuput measure on the rozofsmount
client; it is always enabled.
Regards,
JPierre




Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2016-08-31 14:25 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
Thanks, I'm mostly interested in the storio, as I want to check the performance of the 4 storage nodes I'm monitoring. I have tens of mountpoints and the scheduler I'm using will pick them randomly, so going via storio is probably the best solution.
