### ISSUE TITLE
Provide systemd service files

### ISSUE THREAD

**Issue by rhertzog** [rozofs/rozofs#137]
Most Linux distributions are relying on systemd to initialize the system and manage the services. It would be nice if RozoFS could provide systemd service files natively.

I noticed that Dmitry Smirnov created some initial .services file here, they might help you to get started:
https://github.com/onlyjob/rozofs/commit/6cfa0ccc44a443beb03da6f107185dcc8fe3e3f8

systemd can automatically restart services when they fail so maybe we can get rid of rozolauncher.

**Comment by rozoadrenaline** [comment]
done.
