### ISSUE TITLE
Files tests/fs_ops/fileop/* are not under a free license

### ISSUE THREAD

**Issue by rhertzog** [rozofs/rozofs#140]
[tests/fs_ops/fileop/fileop.c](https://github.com/rozofs/rozofs/tree/e59d0f613a2fe8a2ad2299d715a960efa4416c42/tests/fs_ops/fileop/fileop.c) mentions clearly that you don't have the right to make derivative works:
```
 *  Copyright 2006, 2007, 2008, 2009   Don Capps.
 *
 *  License to freely use and distribute this software is hereby granted 
 *  by the author, subject to the condition that this copyright notice 
 *  remains intact.  The author retains the exclusive right to publish 
 *  derivative works based on this work, including, but not limited to,
 *  revised versions of this work",
```

We dropped those files from the tarball we will ship in Debian because this is not free software. Please get rid of the files too, or get them properly relicensed.

Thank you!

**Comment by rozoadrenaline** [comment]
Those files have been removed since release 2.1.0.
Thank you!
