### ISSUE TITLE
Unable to delete empty directory

### ISSUE THREAD

**Issue by lwandrebeck** [rozofs/rozofs#144]
CentOS 7, rfs 2.0.something (a couple updates since last restart)

[root@master1 ~]# ll -a /rfs/data/4MSDS/3MI/V3.0-HRES/
total 16
drwxr-xr-x. 4 mathieu users 4096 17 janv. 16:58 .
drwxr-xr-x. 7 mathieu users 4096 13 déc.  15:10 ..
drwxr-xr-x. 2 mathieu users 4096 17 janv. 16:55 GEOLOC
drwxr-xr-x. 2 mathieu users 4096 17 janv. 17:06 RADIANCES
[root@master1 ~]# ll -a /rfs/data/4MSDS/3MI/V3.0-HRES/GEOLOC/
total 8
drwxr-xr-x. 2 mathieu users 4096 17 janv. 16:55 .
drwxr-xr-x. 4 mathieu users 4096 17 janv. 16:58 ..
[root@master1 ~]# cd /rfs/data/4MSDS/3MI/V3.0-HRES/
[root@master1 V3.0-HRES]# rmdir GEOLOC/
rmdir: échec de suppression de « GEOLOC/ »: Le dossier n'est pas vide
[root@master1 V3.0-HRES]# rm -rf GEOLOC/
rm: impossible de supprimer « GEOLOC/ »: Le dossier n'est pas vide
(exportd restarted, every storaged restarted, in order to apply 2.1.4. switch to my own machine because /rfs is used by other users on the cluster master)
[root@planchet V3.0-HRES]# cd
[root@planchet ~]# umount /rfs; mount /rfs
[root@planchet ~]# cd -
/rfs/data/4MSDS/3MI/V3.0-HRES
[root@planchet V3.0-HRES]# rmdir GEOLOC/
rmdir: échec de suppression de « GEOLOC/ »: Le dossier n'est pas vide

Nothing special in journalctl. Each storaged restart gave:
janv. 17 17:16:22 master1.hygeos.com storcli[16090]: north_load_balancer_api.c - 239 - warning: north_lbg_userDiscCallBack : LBG node12_c1 entry 0

Nothing in dmesg. Any idea ? mounts have not been restarted as cluster is under load right now.

Thanks and keep up the good work,
Laurent.

**Comment by rozodopamine** [comment]
Could you please provide us with the output of the following command.
It looks like there is a small inconsistency...
attr -g rozofs cd /rfs/data/4MSDS/3MI/V3.0-HRES/GEOLOC

In return I will give you a tip to fix that.
Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-01-17 17:21 GMT+01:00 Laurent Wandrebeck <notifications@github.com>:

**Comment by rozodopamine** [comment]
The correct command is
attr -g rozofs /rfs/data/4MSDS/3MI/V3.0-HRES/GEOLOC
Sorry,
JPierre


Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-01-17 17:28 GMT+01:00 Jean Pierre Monchanin <
jean-pierre.monchanin@rozofs.com>:

**Comment by lwandrebeck** [comment]
attr -g rozofs /rfs/data/4MSDS/3MI/V3.0-HRES/GEOLOC
L'attribut « rozofs » avait une valeur de 442 octets pour /rfs/data/4MSDS/3MI/V3.0-HRES/GEOLOC :
EID     : 1
VID     : 1
LAYOUT  : 1
BSIZE   : 0
NAME    : GEOLOC
FID     : 00000000-0000-4000-f800-00000000611b
SPLIT   : vers=0 mover_idx=0 fid_high=0 recycle=0 opcode=0 exp_id=0 eid=1 usr_id=248 file_id=0 idx=865 del=0 key=3 (DIR)
HASH1/2 : 516cf63c/ed8eda1a (00000094)
UID/GID : 1000007/1000001
CREATE  : Tue Dec 13 15:14:28 2016
XATTR   : NO
I-STATE : 0
MODE    : DIRECTORY
BACKUP  : NO
CHILDREN: 1
NLINK   : 2
SIZE    : 4096
DELETED : 0

**Comment by rozodopamine** [comment]
To fix the directory inconsistency please run the following commands

attr -s rozofs -V " children = 0 " /rfs/data/4MSDS/3MI/V3.0-HRES/GEOLOC
rm -rf /rfs/data/4MSDS/3MI/V3.0-HRES/GEOLOC

Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-01-18 11:05 GMT+01:00 Laurent Wandrebeck <notifications@github.com>:

**Comment by lwandrebeck** [comment]
That did the trick, thanks a lot Jean-Pierre !
Any idea of what could have happened ?
