### ISSUE TITLE
"Connection reset by peer" in exportd, 90% of the nodes can create files, but not read them

### ISSUE THREAD

**Issue by lbeltrame** [rozofs/rozofs#145]
Configuration:
`storage.conf` on 26 nodes: https://gist.github.com/lbeltrame/9a0d03056fae8f818b347e2136c4a825
`export.conf` on export host: https://gist.github.com/lbeltrame/b45f3f830f6453f83a3dbd32a478f60e

Sympthoms:

On export host:

```
echo "test" > foo.bar
cat foo.bar
test
```

On any other host that has the volume mounted:

```
echo "test" > foo.bar
cat foo.bar
cat: foo.bar: Input/output error
```

The actual file is empty when read from the host that can read it.

Exportd logs when a volume is mounted:

```
gen 31 09:21:42 mn-00 exportd[1180]: eproto_nb.c - 630 - info: 172.16.251.141 mounting export 1 on path /srv/rozofs/exports/export_1 : allowed
gen 31 09:21:42 mn-00 exportd[1180]: af_unix_socket_stream_recv.c - 135 - warning: af_unix_recv_stream_sock_recv Connection reset by peer
```

All the machines have no firewall (except the export host) and they are all reachable among each other (they share the same subnet).

**Comment by rozodopamine** [comment]
It looks like the the mount point has access to the exportd but not to the
storages.
Please run the following commands on a node that can not read/write:
rozodiag -T mount:0 -c all
rozodiag -T mount:0:1 -c all
and send us the display.
Thanks,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-01-31 9:23 GMT+01:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
Thanks for the reply. I have put the output in a gist: https://gist.github.com/lbeltrame/373753d0c2afbab3f96db7ef85c19ea8

**Comment by lbeltrame** [comment]
And the output of the second command: https://gist.github.com/lbeltrame/b3e0a65a8c9917385cbd64c9534f2616

**Comment by lbeltrame** [comment]
Well, the weird thing is that now it's working... ;) 
I changed the mount options from

```
noauto,instance=0,exporthost=172.16.251.140,exportpath=/srv/rozofs/exports/export_1,posixlock,bsdlock,_netdev
```
to
```
noauto,exporthost=mn-00,exportpath=/srv/rozofs/exports/export_1,_netdev
```
and restarted rozofsmount. Apparently that was enough for the issue to solve. I'll close this for now and reopen if the problem reappears.
