### ISSUE TITLE
Accessing files on some (not all) nodes yields EINVAL

### ISSUE THREAD

**Issue by lbeltrame** [rozofs/rozofs#153]
I have a RozoFS setup with 4 storage nodes and 1 export hosts, and additional 11 nodes which only act as client (they use rozofsmount to mount).

When accessing some files, some nodes report errors in the form of "no such file or directory" or EINVAL ("Invalid argument"). 

```
$ ssh goodnode "cat /rozomount/annotations.txt" > /dev/null
$

$ ssh badnode "cat /rozomount/annotations.txt" > /dev/null
cat: rozomount/annotations.txt: Invalid argument
```

"badnode" and "goodnode" are both up to date with RozoFS packages.

**Comment by rozodopamine** [comment]
Could you please run rozo_dumpcnf on goodnode as well as badnode
and send us back the result files.
Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-07-11 13:44 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
I'll send the files via mail now.

**Comment by rozodopamine** [comment]
From the dumps you have sent it looks like rozofsmount should be mounted on
/data so why are you requesting files under /rozofsmount.?
I would like to get the result of "rozodiag -T mount:0 -c all' on good and
bad node if you rozofsmount instance is 0.
Regards,
JPierre


Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-07-11 15:39 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
Sorry, I forgot to mention this (and the other report too), the paths are "anonymized" in public reports.

**Comment by lbeltrame** [comment]
Good node: https://gist.github.com/lbeltrame/6a792efe5be79cc7afeef2c15d930eae
Bad node: https://gist.github.com/lbeltrame/d692bb1907a08d6fab7068dd5da10a24

**Comment by rozodopamine** [comment]
It looks like there is lots of timeout on the rozofsmount although the
timers are very high
____[rozofsmount 0]__[trx]____
number of transaction contexts (initial/allocated) : 128/0
context size (bytes)                               : 264
Total memory size (bytes)                          : 33792
Statistics
TX_SEND           :   37104675
TX_SEND_ERR       :          0
TX_RECV_OK        :   37093818
TX_RECV_OUT_SEQ   :      10567
TX_TIMEOUT        :      10857
TX_ENCODING_ERROR :          0
TX_DECODING_ERROR :          0
TX_CTX_MISMATCH   :          0
TX_NO_CTX_ERROR   :          0
TX_NO_BUFFER_ERROR:          0

Your system looks very slow just like if flow control was not activated on
your network ?
Flow control is not not an option, It has to be activated.

On the bad node we will make a trace on rozofsmount to figure exactly what
is wrong..
Activate the trace this way:
rozodiag -T mount:0 -c trc enable -c trc count 400

Then run the test
cat /rozomount/annotations.txt

run and finally dump the trace
rozodiag -T mount:0 -c trc

Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-07-11 17:04 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
I have checked the switches (Cisco 2960) and flow control should be on: those machines are all on the same switches, also. But just in case, I'll double check.

As for the trace:

```
 rozodiag -T mount:0 -c trc
____[rozofsmount 0]__[trc ]____
trace entry size : 152 Bytes
ino size         : 8 Bytes
[           0 ]--> getattr     0 17c0000000000972 00000000-0000-0000-0000-000000000000
[       56128 ]<-- getattr     0 000000000000 00000000-0000-4000-7209-00000000c017 0:Success      765
[     8398610 ]--> open        1 17c0000000000972 00000000-0000-0000-0000-000000000000 (0100000)
[      101261 ]<-- open        1 7f58a0eb8c80 00000000-0000-4000-7209-00000000c017 0:Success      765
[      145322 ]--> read        2 7f58a0eb8c80 00000000-0000-4000-7209-00000000c017        0/4096
[      319891 ]<-- read        2 7f58a0eb8c80 00000000-0000-4000-7209-00000000c017 22:Invalid argument
[       28235 ]--> read        3 7f58a0eb8c80 00000000-0000-4000-7209-00000000c017        0/4096
[      133608 ]<-- read        3 7f58a0eb8c80 00000000-0000-4000-7209-00000000c017 22:Invalid argument
[       97650 ]--> getattr     4 17c0000000000972 00000000-0000-0000-0000-000000000000
[       23668 ]<-- getattr     4 000000000000 00000000-0000-4000-7209-00000000c017 0:Success      765
[      265642 ]--> read        5 7f58a0eb8c80 00000000-0000-4000-7209-00000000c017        0/4096
[      128547 ]<-- read        5 7f58a0eb8c80 00000000-0000-4000-7209-00000000c017 22:Invalid argument
[  2400153494 ]--> flush       6 7f58a0eb8c80 00000000-0000-4000-7209-00000000c017        0/0
[       14701 ]<-- flush       6 7f58a0eb8c80 00000000-0000-4000-7209-00000000c017 0:Success
[       93223 ]--> release     7 7f58a0eb8c80 00000000-0000-0000-0000-000000000000
[      114981 ]<-- release     7 7f58a0eb8c80 00000000-0000-4000-7209-00000000c017 0:Success
```

**Comment by rozodopamine** [comment]
Hi Luca,
in the latest releases we have increased the size of share memory that we
use in the rozofsmount.
We use up to 52428800 bytes of share memory. This amount is over the
maximum  allowed in debian wheezy.
I do not known about your ubuntu release.
Could you check the content of /proc/sys/kernel/shmmax ?
If the value is lower than 52428800 please set it to 52428800:
echo 52428800 >  /proc/sys/kernel/shmmax
Then please unmount and then remount rozofsmount.
For a permanent change set
kernel.shmmax=52428800
it in /etc/sysctl.conf.
Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-07-12 13:55 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by rozodopamine** [comment]
By the way can you provide us with the result of
rozodiag -T mount:0:1 -c all
from the bad node.
Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-07-12 14:32 GMT+02:00 Jean Pierre Monchanin <
jean-pierre.monchanin@rozofs.com>:

**Comment by rozodopamine** [comment]
ps -ef | grep STORCLI
would also be helpfull to check how many STORCLI processes are running.

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-07-12 14:46 GMT+02:00 Jean Pierre Monchanin <
jean-pierre.monchanin@rozofs.com>:

**Comment by lbeltrame** [comment]
The value for echo /proc/sys/kernel/shmmax was lower: raising it did not make a difference but as it's set lower by default I'll push this change to all nodes nevertheless.

The output on the bad node is: https://gist.github.com/lbeltrame/1ac1b62becb45a37a6e403f128360d8b

**Comment by lbeltrame** [comment]
As for storcli processes, it looks like there's just one:

```
ps -ef | grep storcli
root      4924  4920  0 15:25 ?        00:00:00 rozolauncher start /var/run/launcher_rozofsmount_0_storcli_1.pid storcli -i 1 -H node253 -o rozofsmount -E /srv/rozofs/exports/NGS -M /rozomount -g 0 -D 50004 -R 0 --shaper 0 -s 30 -t 15000 -k 1380932144 -l 528384 -c 32 -L 0 -B 0
root      4925  4924  0 15:25 ?        00:00:00 storcli -i 1 -H node253 -o rozofsmount -E /srv/rozofs/exports/NGS -M /rozomount -g 0 -D 50004 -R 0 --shaper 0 -s 30 -t 15000 -k 1380932144 -l 528384 -c 32 -L 0 -B 0
einar     6585  6462  0 15:30 pts/3    00:00:00 grep --color=auto storcli
```

`node253` is the export host.

**Comment by rozodopamine** [comment]
Luca,
your bad node is not able to connect to the storage nodes at address
192.168.5.{249..252}.
Could try some pings from bad node ?

Then if the ping works, check that the storage nodes are started.
for i in {249..252}
do
  rozodiag -i 192.168.5.$i -T storaged -c cpu
done

Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-07-12 15:31 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
In data mercoledì 12 luglio 2017 15:50:06 CEST, rozodopamine ha scritto:

> your bad node is not able to connect to the storage nodes at address
> 192.168.5.{249..252}.
> Could try some pings from bad node ?

Interesting! I moved the storage nodes to a different subnet to remove the 
traffic from the main subnet. I thought the nodes doing mount would only go 
through the export host for mounting, and ever access the storage nodes 
directly.

Is this not the case? If so, I'll need to adjust routing.

**Comment by rozodopamine** [comment]
The client (rozofsmount process) does access to the export. The client
(STORCLI process) also accesses the storages.


[image: Images intégrées 1]

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-07-12 15:59 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
I fixed routing and now the bad nodes can access the files. Thanks for the help! I'll close this now.
