### ISSUE TITLE
Log flood in case of errors

### ISSUE THREAD

**Issue by lbeltrame** [rozofs/rozofs#155]
One of my RozoFS installs had a number of nodes failing (old hardware...) but it needs to run even if not in optimal state as an interim (it wil get replaced soon). 

However, exportd spams the log with errors related to at least one node:

```
Sep  4 09:40:57 uni11 export_slave_1[10359]: export_tracking.c - 4542 - severe: lookup_cnx failed FID 00000000-0000-4000-0403-000000002414 trash inode 00000000-0000-4000-9100-00000000d40e cid 1 sid 5
```
It made the syslog grow up to 2G in size and got close to filling up the partition. Can this be at least silenced? 

Not a problem if it can't be done (I put stronger log rotation options for the moment).

**Comment by rozodopamine** [comment]
Luca,
could you please provide me with the output of this rozodiag command :
rozodiag -T export:1 -c all
Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-09-04 9:43 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
Hello Jean-Pierre,

here it is: https://gist.github.com/lbeltrame/aff763926e56c5d50a7e6f21ac37321c

**Comment by lbeltrame** [comment]
For the record and just to make things clear: I'm fully aware that this setup is now in a very sub-optimal state. The hardware will be replaced soon, so this is mostly as a "convenience" until that happens.

**Comment by rozodopamine** [comment]
Luca,
the ouput of the CLI is truncated. The result of
rozodiag -T export:1 -c vfstat_stor
is missing.
Nevertheless, I have got the feeling that you have shrinked down the
configuration by removing cid 1 sid 5 from the exportd.conf configuration,
which is not a legal action supported by RozoFS.
Regards,
JPierre


Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2017-09-04 10:32 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
Thanks, I re-added it (although the node is down) and I let exportd deal with its absence. Closing.
