### ISSUE TITLE
Hardcoded FD limit for exportd breaks setups with many small files

### ISSUE THREAD

**Issue by lbeltrame** [rozofs/rozofs#159]
One of my HPC applications generates many, many small files in order to increase parallelism. The problem is that this makes exportd run out of file descriptors and thus everything breaks. While I have upped the limit already, to my dismay I found that it's hardcoded in exportd itself:

```c
#define EXPORTD_MAX_OPEN_FILES 5000
```
Can this be made configurable? 5000 is on the low side for most file-intensive applications.

**Comment by rozodopamine** [comment]
We are not sure at all that your problem is related to this constant. Could
please recreate lots of files
and at this time run the following diagnostic command on the node hosting
the master export
for i in {0..8}
do
  rozodiag -T export:$i -c all
done

and on a node running the rozofsmount (its up to you to determine the
instance)

rozodiag -T mount:<instance> -c all

Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2018-03-27 9:20 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
While I generate those files (shortly, hopefully), I'll also paste the output from the syslog which outlines the problem:

```
Mar 27 07:35:30 santabarbara export_slave_1[7892]: dirent_cache.c - 1611 - severe: Cannot open the file d_0, error Too many open files at line 1611
Mar 27 07:35:30 santabarbara export_slave_1[7892]: export_tracking.c - 838 - severe: No bitmap pointer
Mar 27 07:35:30 santabarbara export_slave_1[7892]: dirent_cache.c - 1611 - severe: Cannot open the file d_1, error Too many open files at line 1611
Mar 27 07:35:30 santabarbara export_slave_1[7892]: export_tracking.c - 838 - severe: No bitmap pointer
Mar 27 07:35:30 santabarbara export_slave_1[7892]: dirent_cache.c - 1611 - severe: Cannot open the file d_2, error Too many open files at line 1611
Mar 27 07:35:30 santabarbara export_slave_1[7892]: export_tracking.c - 838 - severe: No bitmap pointer
Mar 27 07:35:30 santabarbara export_slave_1[7892]: dirent_cache.c - 1611 - severe: Cannot open the file d_3, error Too many open files at line 1611
Mar 27 07:35:30 santabarbara export_slave_1[7892]: export_tracking.c - 838 - severe: No bitmap pointer
Mar 27 07:35:30 santabarbara export_slave_1[7892]: dirent_cache.c - 1611 - severe: Cannot open the file d_4, error Too many open files at line 1611
Mar 27 07:35:30 santabarbara export_slave_1[7892]: export_tracking.c - 838 - severe: No bitmap pointer
```

I also need to point out that this something "incremental": it shows usually after 1-2 weeks of continuous usage.

**Comment by rozodopamine** [comment]
Luca,
it looks like the exportd has lost some file descriptors. In order to check
that, I send you a python script
to run on the exportd master node. It will make the list of opened files
and sockets by the exportd
processes.
Regards,
JPierre



Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2018-03-27 9:46 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
Was it attached? (in this case GH stripped it off the mail, I think). In any case, here are the information requested:

https://gist.github.com/c288244b12f3145db4941cec39330140

Bear in mind that I had to restart exportd as I needed to continue operations.

**Comment by rozodopamine** [comment]
Do not forget to run rozo_getexport_fd script that I sent to you in my
previous mail.

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2018-03-27 10:44 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
I think the GH mails have removed the attachment and thus the script. Can you pastebin or put it on a Gist?

**Comment by rozodopamine** [comment]
#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import os.path
import subprocess
import time
import re
import shlex
from optparse import OptionParser

def get_export_pid(index):
  string="rozodiag -T export:%s -c ps"%(index)
  parsed = shlex.split(string)
  cmd = subprocess.Popen(parsed, stdout=subprocess.PIPE,
stderr=subprocess.PIPE)

  # loop on the bins file constituting this file, and ask
  for line in cmd.stdout:
    words=line.split();
    if len(words) < 4: continue
    if words[0] == "Blocking": return words[1]
  return None


for index in range(8):
  pid = get_export_pid(index)
  string = "ls -lisa /proc/%s/fd/"%(pid)
  print "\n\n______________EXPORT %s PID %s"%(index,pid)
  os.system(string)


Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2018-03-27 11:27 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
Thanks. The output is at https://gist.github.com/lbeltrame/801f474de8bd81a4481eafa7f50e2a7e

**Comment by rozodopamine** [comment]
Thanks Luca,
the exportd process is actually loosing some file descriptors. We will
prepare a fix for this problem.
Nevertheless the fd are lost while the exportd has problem write the
meta-data device.
Could you please send the ouput of the following diagnostic command on the
export node.
rozodiag -T export:1 -c all


Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2018-03-27 11:42 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
And here's the requested output: https://gist.github.com/148992094ba374161f63ecf503a9a672

**Comment by rozodopamine** [comment]
Luca,
release 2.6.2 of RozoFS fixes the definitive loss of file descriptors that
you have encountered in the exportd process,
Nevertheless the loss only occurs while encountering an error writing on
the meta-data device on a user directory
creation. We do not know what caused the initial error (either software,
hardware, device full) and whether you will
reproduce or not this case...
Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2018-03-27 13:11 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by rozodopamine** [comment]
Luca,
is the 2.6.2 fix any good for your problem ?

**Comment by lbeltrame** [comment]
I haven't been able to properly verify this yet. It takes quite a while for the problem to manifest itself. I'll keep an eye on the exportd fd usage.

**Comment by lbeltrame** [comment]
It looks like it's behaving properly now. Closing.
