### ISSUE TITLE
Low performance on deeply nested directory trees and large file numbers

### ISSUE THREAD

**Issue by lbeltrame** [rozofs/rozofs#160]
cc @tony-travis

I've noticed on our RozoFS cluster that performance can be extremely poor when operating with deeply nested directory trees.  For example, deleting a series of folders and files (111636 entries in total) can take more than two hours. On the same page, even basic operations which require `stat()` calls can take one or two seconds, and reading and writing operations can time out leading to what was observed in issue #148 (I didn't follow up there due to time constraints: my apologies). 

Some diagnostic information on exports and timers are provided at https://gist.github.com/lbeltrame/806a78e2d393f3dba58a1ed6779cd835.

**Comment by rozodopamine** [comment]
Hi Luca,
can you provide the characteristics of your meta-data device : HDD or SDD
(which model).
Are you securing your meta-data using drbd ?
Can you run "rozo_device" on the active export.
Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2018-06-06 9:32 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
The meta-device uses HDDs arranged in a RAID10 configuration and using drbd in primary/secondary mode (drbd connection occurs on a dedicated NIC):

```
cat /proc/mdstat 
Personalities : [linear] [multipath] [raid0] [raid1] [raid6] [raid5] [raid4] [raid10] 
      
md1 : active raid10 sdf1[5] sdh1[8] sde1[4] sdg1[6] sdd1[3] sdc1[2] sdb1[1] sda1[0]
      23441557504 blocks super 1.2 512K chunks 2 near-copies [8/8] [UUUUUUUU]

drbd driver loaded OK; device status:
version: 8.4.5 (api:1/proto:86-101)
srcversion: 4B3E2E2CD48CAE5280B5205 
m:res  cs         ro                 ds                 p  mounted              fstype
0:r0   Connected  Primary/Secondary  UpToDate/UpToDate  C  /srv                 ext4
```

Each disk is a 6T disk (not particularly fast, unfortunately).

I don't have rozo_device as available command (up to date RozoFS stable on Ubuntu 14.04).

**Comment by rozodopamine** [comment]
Accesses to the meta-devices are only small random read/writes and no
sequential. For this reason RAID0 do not help to
speed up the meta-data operations. Disks are usually to slow for the
meta-data operations. For this reason we only use
SSD or NVME as meta-data devices. On each export node we have a RAID1 on 2
SSD/NVME + drbd between 1 nodes.
We have some questions:
- You say deleting files takes hours. Do you mean the rm command is long,
or it is long to to get free space back ?
- What is the speed of your NIC dedicated to drbd ?
- You have almost 2TB used on your meta-data device which is huge. Do you
use this device for something else
     than RozoFS meta-data.?
Regards,
JPierre


Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2018-06-06 10:31 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by lbeltrame** [comment]
> - You say deleting files takes hours. Do you mean the rm command is long, or it is long to to get free space back ?

The actual command. I do a rm -fr * inside one of these trees, the time it takes is extremely long

> - You have almost 2TB used on your meta-data device which is huge. Do you use this device for something else

Yes, mostly for bits that are shared r/o elsewhere.

**Comment by rozodopamine** [comment]
You should not use the meta-data devices for something else than RozoFS
meta-data,
and if meta-data performance is important for you (which is the case of all
our customer),
you should not use HDD as meta-data device but rather HDD or NMVE as we
always do
for our customers.
Regards

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2018-06-06 14:28 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by rozoadrenaline** [comment]
During the `rm -fr *` It could be interesting to launch (on the master
export server) these commands:

- `iostat -dxm` for seeing if HDD devices are IO bound. (util=100%) (could
be the HDDs or the networking)
- `top` or `htop` for seeing if the export is CPU bound

Regards.





Sylvain DAVID
R&D Engineer

+33.2.51.85.74.21
sylvain.david@rozofs.com <sylvain.david@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs

2018-06-06 15:25 GMT+02:00 rozodopamine <notifications@github.com>:

**Comment by lbeltrame** [comment]
iostat -dxn
```
 sudo iostat -dxm
Linux 4.4.0-119-generic (santabarbara)  06/06/18        _x86_64_        (12 CPU)

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda              20.37     0.27   22.11    0.62     2.66     0.00   239.72     0.73   32.05   29.89  108.64   3.77   8.57
md1               0.00     0.00    1.12    2.26     0.19     0.02   123.43     0.00    0.00    0.00    0.00   0.00   0.00
sdb              23.49     0.27   18.81    0.62     2.65     0.00   280.05     0.77   39.42   37.12  108.81   4.42   8.58
sdc              18.71     0.25   23.70    0.57     2.66     0.00   224.51     0.68   28.06   25.80  121.41   3.61   8.77
sdd              17.53     0.25   24.75    0.57     2.65     0.00   214.84     0.74   29.25   27.16  119.64   3.46   8.76
sde               1.70     0.25   40.65    0.56     2.66     0.00   132.23     0.16    3.77    2.39  104.78   1.79   7.39
sdf               1.53     0.25   40.75    0.56     2.65     0.00   131.71     0.16    3.84    2.48  103.54   1.77   7.30
sdg               1.30     0.24   41.05    0.62     2.66     0.00   130.76     0.15    3.51    2.13   95.23   1.78   7.43
sdh               1.07     0.24   41.21    0.62     2.65     0.00   130.08     0.14    3.29    1.98   90.54   1.70   7.09
sdi               2.45     4.28    1.14    3.29     0.22     0.06   128.32     0.07   16.74    7.19   20.05   3.62   1.60
md0               0.00     0.00    0.09    7.02     0.00     0.06    16.69     0.00    0.00    0.00    0.00   0.00   0.00
sdj               2.97     4.28    0.56    3.29     0.22     0.06   146.59     0.08   21.26   19.92   21.49   4.45   1.72
drbd0             0.00     0.00    0.81    2.26     0.13     0.02    97.13     0.90  292.71   15.28  391.74  68.28  20.90
```

CPU usage on the export node has md/raid (up to 5%) and storcli (up to 10%) as the highest CPU using processes.

**Comment by rozoadrenaline** [comment]
Is-it possible to know which NIC (speed and vendor) is used for DRBD transfer ?
Could you also check the device scheduler used for metadata HDDs ? `lsblk -t`
You could also check if NIC IRQs are not too high (one CPU core at 100%) for the NIC via `htop` ?
Regards.

**Comment by rozodopamine** [comment]
The iostat output shows that your drbd0 device is slow. Await is 292.71
ms.
Use SSD as meta-data device. You will get much better performances on
meta-data operations.
Here is an example of what we can get with 1Gb/s ethernet links.

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz
avgqu-sz   await r_await w_await  svctm  %util
sda               0,01     2,84    0,15    2,55     0,00     0,04    33,25
   0,01    2,57    0,82    2,67   0,41   0,11
dm-0              0,00     0,00    0,03    3,61     0,00     0,03    14,61
   0,01    1,61    0,50    1,61   0,19   0,07
dm-1              0,00     0,00    0,00    0,00     0,00     0,00     8,00
   0,00    1,27    1,27    0,00   0,08   0,00
dm-2              0,00     0,00    0,00    0,00     0,00     0,00     3,33
   0,00    1,48    1,51    0,00   0,02   0,00
dm-3              0,00     0,00    0,04    1,19     0,00     0,00     7,98
   0,00    0,67    0,16    0,68   0,28   0,03
dm-4              0,00     0,00    0,09    0,16     0,00     0,01   106,68
   0,00   18,70    1,22   28,97   0,47   0,01
drbd0             0,00     0,00    0,04    1,19     0,00     0,00     7,93
   0,00    2,41    0,13    2,48   0,71   0,09

Regards,
JPierre

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*



2018-06-06 17:09 GMT+02:00 Luca Beltrame <notifications@github.com>:

**Comment by rozonicotine** [comment]
Metadata should be on SSD not HDD.
