### ISSUE TITLE
Allow to run in foreground

### ISSUE THREAD

**Issue by kvaps** [rozofs/rozofs#161]
Add `-f` option for prevent process forking:

* `exportd -f`
* `storaged -f`
* `rozofsmount -f`
* `rozo agent start -f`

It is necessary step for allow running via docker without wrapper scripts and good practic for run using systemd.

It would be much better if all logs in this mode would send directly to `/dev/stdout` and `/dev/stderr`, without the needs of rsyslog daemon.

**Comment by rozonicotine** [comment]
We have good reason to not doing it and we will not go that way.
If you really want to do it, we can do it on our thanks a script

Best Regards

**Comment by rozonicotine** [comment]
This request is closed
