### ISSUE TITLE
2.12.1: FTBFS "/usr/share/dpkg/no-link.specs: No such file or directory"

### ISSUE THREAD

**Issue by onlyjob** [rozofs/rozofs#163]
Unusual build failure on Debian 10 "Buster":

~~~~
/usr/include/x86_64-linux-gnu/bits/stdio2.h:33:10: note: '__builtin___sprintf_chk' output between 3 and 1028 bytes into a destination of size 1024 
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1, 
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
       __bos (__s), __fmt, __va_arg_pack ()); 
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-rHYsq1/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -specs=/usr/share/dpkg/no-link.specs -Wl,-z,relro -Wl,-z,now -g -O2 -fdebug-prefix-map=/build/rozofs-2.12.1=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-2.7/build/rozofs-2.12.1/manager/rozofs/core/libconfig_wrap.o -lconfig -o build/lib.linux-x86_64-2.7/rozofs/core/_libconfig.so                                                                                  
x86_64-linux-gnu-gcc: error: /usr/share/dpkg/no-link.specs: No such file or directory 
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1 
~~~~

**Comment by rozodopamine** [comment]
We do not yet package RozoFS for buster.

**Comment by rozodopamine** [comment]
The problems seams to be linked to a new control in Buster packaging into
which libconfig falls.
We will take care of it when we will work on packaging for Buster.

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*




Le mer. 29 août 2018 à 10:23, Dmitry Smirnov <notifications@github.com> a
écrit :
