### ISSUE TITLE
Packaging: Ubuntu 14.04 EOL in April 2019

### ISSUE THREAD

**Issue by lbeltrame** [rozofs/rozofs#164]
As the subject says, April 2019 will mark EOL for Ubuntu 14.04, which is the only Ubuntu version available on dl.rozofs.org. Are there any plans to introduce packaging for 16.04 and 18.04? 

This would help transitions when migrating.

**Comment by rozoadrenaline** [comment]
The "develop" branch is now builded on ubuntu 18.04.  The master also will follow when the develop becomes master.
Regards.
