### ISSUE TITLE
No space left on device though it’s « only » 96% full

### ISSUE THREAD

**Issue by lwandrebeck** [rozofs/rozofs#165]
CentOS 7.5 (also tested a client running 7.6 with CR repository)

```
$ LANG=C echo "bla" > /rfs/bla
bash: /rfs/bla: No space left on device
$ df -h | grep rfs
rozofs                                88T     83T  4,4T  96% /rfs
$ LANG=C touch /rfs/bla
touch: cannot touch '/rfs/bla': No space left on device
```

Everything was running fine before that. Exportd has been restarted, and mount point remounted. Nothing fishy appears in logs. Reading an existing file is still OK.
Any idea ?

Thanks,

**Comment by lwandrebeck** [comment]
Hmmmmmmmm, little update, it looks like it does not come from the update, but due to the FS being filled up, though it indicates being « only » 96% full

**Comment by lwandrebeck** [comment]
To be clearer, deleting some data to free some space up allows to write again.
storaged boxes use raid0 xfs formatted disks with rw,noatime,seclabel,attr2,inode64,sunit=1024,swidth=2048,noquota if that can help to track down the problem.

**Comment by rozodopamine** [comment]
In release 2.14.0 has been added a control : When letf space is under **minimum_free_size** percent the file/directory creation fails with ENOSPACE. Neverthelesss it is still possible to read the files, and still possible to write the existing files.

The value of **minimum_free_size** can be set in /etc/rozofs/rozofs.conf of the export nodes. 
The default value is 4%.  

You can lower this value if you like.  For instance set a value of 2%:
   minimum_free_size = 2; 
and make the export reread this file :
   rozodiag -T export:0-8 -c cc reload

Nevertheless it is not safe to run without space left. It could lead to some writting errors that may
corrupt the written files.
