### ISSUE TITLE
rpm gpg signing is broken

### ISSUE THREAD

**Issue by lwandrebeck** [rozofs/rozofs#166]
Hi,
It’s been a couple versions where gpg signing is broken, at least on CentOS 6 and 7.
Could you fix it up, please ?
Thanks and keep up the good work !

**Comment by rozoadrenaline** [comment]
Hi,

I think it's fixed now. Could you check it and confirm, please ?
Regards.

**Comment by lwandrebeck** [comment]
Hi,

rozofs-rozofsmount-2.21.13-1.el7.centos.x86_64.rpm installed without complaining, thanks !

**Comment by lwandrebeck** [comment]
Hi,

Looks like signature failed again on 2.21.14.
Could you fix that up please ?
Best,

**Comment by rozodopamine** [comment]
Can you check whether the problem is fixed.

**Comment by rozodopamine** [comment]
Can you check whether the problem is fixed.

Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*

**Comment by lwandrebeck** [comment]
Update on a client went fine now, thanks !
