### ISSUE TITLE
Debian build: Failure on override_dh_strip

### ISSUE THREAD

**Issue by drazzib** [rozofs/rozofs#82]
Hi,

I've tried to build rozofs current master branch in a clean Debian unstable chroot (using [sbuild](https://wiki.debian.org/sbuild)). Here is the instruction, I've followed :

```
dpkg-buildpackage -S
sbuild -d unstable -Asn ../rozofs_1.5.2.dsc
```

But dh_strip debhelper call fail inside this chroot with the following message

```
dh_strip --dbg-package=rozofs-dbg
mkdir -p /«PKGBUILDDIR»/debian/rozofs-dbg/usr/lib/debug/usr/lib/pymodules/python2.7
mv /«PKGBUILDDIR»/debian/rozofs-dbg/usr/lib/debug/usr/lib/pyshared/python2.7/rozofs \
   /«PKGBUILDDIR»/debian/rozofs-dbg/usr/lib/debug/usr/lib/pymodules/python2.7/rozofs
mv: cannot stat '/«PKGBUILDDIR»/debian/rozofs-dbg/usr/lib/debug/usr/lib/pyshared/python2.7/rozofs': No such file or directory
make[1]: *** [override_dh_strip] Error 1
debian/rules:23: recipe for target 'override_dh_strip' failed
```

I fail to see what you are trying to achieve with mv call in debian/rules (ie. if I remove it, package build successfully from source)

Regards,

**Comment by rozonicotine** [comment]
Deprecated
