### ISSUE TITLE
dangerous use of "fatal()"

### ISSUE THREAD

**Issue by onlyjob** [rozofs/rozofs#85]
`fatal()` messages can cripple system. With improperly configured storaged I just experienced flood of messages like

~~~~
Message from syslogd@deblab at Dec  3 09:05:10 ...
 storio[31964]: storio_north_intf.c - 332 - fatal: Can't create AF_INET listening socket 0.0.0.0:41001

Broadcast message from systemd-journald@deblab (Wed 2014-12-03 09:05:10 AEDT):

storio[31964]: storio_north_intf.c - 332 - fatal: Can't create AF_INET listening socket 0.0.0.0:41001


Message from syslogd@deblab at Dec  3 09:05:13 ...
 storio[31970]: storio_north_intf.c - 332 - fatal: Can't create AF_INET listening socket 0.0.0.0:41001

Broadcast message from systemd-journald@deblab (Wed 2014-12-03 09:05:13 AEDT):

storio[31970]: storio_north_intf.c - 332 - fatal: Can't create AF_INET listening socket 0.0.0.0:41001
~~~~

to all consoles which pretty much paralised work as it is impossible to use text editor when error distort terminal every 3rd second. With some effort I was able to kill storage daemon but I had to do it blindly as I could not even inspect logs. This is dangerous and extremely disturbing way of notifying about errors. Please throttle or better just direct such messages to logs. Thanks.

Background: I was setting-up new storage node where storaged was installed (and apparently started) with default `/etc/rozofs/storaged.conf`. I installed `rozofs-storaged_1.5.4-1_amd64.deb` which seems to start (second copy of?) storaged right away and that's how it started...

**Comment by rozodopamine** [comment]
Fixed and delivered
