### ISSUE TITLE
client not reloading configuration?

### ISSUE THREAD

**Issue by onlyjob** [rozofs/rozofs#86]
I'm setting up my first cluster and I've mounted `/mnt/rozofs` when only 3 storage devices was configured (`layout=0`). Naturally mount point did not allow me to write files (expected). However when I added 2 more storage devices and restarted `exportd` an attempt to read/write a file on mount point failed with 

```
rozofsmount[24575]: rozofs_write.c - 1720 - severe:  transaction error Timer expired
```

logged to `syslog`. Umounting failed as well:

```
fusermount: failed to unmount /mnt/rozofs: Device or resource busy
```

After forced (i.e. "lazy") umount (`fusermount -uz /mnt/rozofs`) I mounted RozoFS again and it worked just fine. I'm not too sure whether this problem is because client failed to reload configuration from `exportd` or if some safeguards were ignored on first mount... Experienced on 1.5.4.

**Comment by rozonicotine** [comment]
Deprecated
