### ISSUE TITLE
storaged: detect mount point

### ISSUE THREAD

**Issue by onlyjob** [rozofs/rozofs#88]
It is probable that failed storage HDD will not be mounted to corresponding mount point. However in such case `rozofs-storaged` still creates its files in designated "root" directory as configured in `/etc/rozofs/storage.conf`. Unfortunately lack of mount point detection lead to possibility that `rozofs-storaged` will work in rootfs instead of storage mount. Such scenario is quite possible when server is rebooted but dead storage HDD were not mounted. Such error would be hard to detect as RozoFS storage daemon starts like everything is OK.

Please consider detecting whether configuring storage root is mounted and fail to start corresponding storage if it isn't.

**Comment by rozodopamine** [comment]
With the introduction of the automount feature, the storage detects the devices and their role and mount them at the right place.
