### ISSUE TITLE
random read/write errors

### ISSUE THREAD

**Issue by onlyjob** [rozofs/rozofs#90]
Client sometimes return spurious read or write errors but re-trying operation usually succeed. Not sure if I can provide more details -- I see no errors in logs whatsoever and strangely enough RozoFS daemons do not log anything (?)... There is nothing related to RozoFS in `syslog`... Because those errors manifest some time since the beginning of intensive read or write operations (i.e. `rsync`) I suspect some kind of buffering issue in client but this is merely my guts feeling...

**Comment by rozodopamine** [comment]
we had a problem with rsync in old times, but it has been fixed a long time ago.
This issue should be closed.
