### ISSUE TITLE
Support Nagios/Ganglia/Icinga (+?) monitoring

### ISSUE THREAD

**Issue by lwandrebeck** [rozofs/rozofs#91]
Hi,

each of us know distributed FS are used for quite huge needs, so we need to integrate nicely in huge structures.
Nagios (+ Icinga ?), and Ganglia are quite often used by cluster sysads. So adding support for these solutions would be a real plus.
As a Ganglia user, I’ll be glad to provide help and testing.

**Comment by rozonicotine** [comment]
Plugins are available for Nagios and Zabbix up to now
