### ISSUE TITLE
`rozo` issue when performing 'node start/stop' (with missing packets ?)

### ISSUE THREAD

**Issue by dpertin** [rozofs/rozofs#95]
I am experimenting RozoFS on [Docker](https://www.docker.com/) whose images should embed as few packages as possible to be light. My images are based on the [official Debian repo](https://registry.hub.docker.com/_/debian/) which is very lightweight.

When I'm launching `rozo node stop -r exportd -E localhost` on `exportd` I am surprisingly facing [file existence issues](http://pastebin.com/b6cFukhi) until I install `syslog-ng` ... I decided to install syslog-ng to get any clue on the problem but it appears to solve it. However, I don't understand why it (or dependencies) is required.

[Here](http://pastebin.com/WKAxqMLk) is the same command as above given parameter `-d`.

**Comment by rozonicotine** [comment]
Obsolete : rozo tool is not used anymore
