### ISSUE TITLE
Number of storage supports in export.conf no checked

### ISSUE THREAD

**Issue by dpertin** [rozofs/rozofs#96]
Hello,

We faced an issue this morning given that `exportd` started well without giving warnings in logs whereas the number of storage nodes in our volume were seven and the layout were set to 1 (requiring 8 storage nodes to be defined).

Surprisingly, errors appears when a client try to write on the mounted FS:

```
root@r2d2:/mnt/rozofs# cp ~/Bureau/yolo.mp4 ./loul.mp4
cp: impossible de créer le fichier standard «./loul.mp4»: Aucun espace disponible sur le périphérique
```

This error implies the lack of storage capacity in the target FS while a `df` shows it is empty and able to receive data.

This situation surprised me since any missing storage node should not disturbed the system. It might be a problem during a service start but no error seems to appear. I think the problem should be checked when `exportd` boots.

In the investigation of the issue, the amazing `rozodiag` tool show the missing of a storage node.
Since the number only available servers were 7 I put a new directory on the last one and defined it as a new storage support identified as the eighth `sid`. Once the storaged was restarted, the write operation was able to be done.

**Comment by rozonicotine** [comment]
Done
