### ISSUE TITLE
Still able to write after exceeding HQuota 

### ISSUE THREAD

**Issue by stalob** [rozofs/rozofs#98]
Hello,

I faced an issue when I wrote on an export with an hard quota of 2 TB

The system wrote into the export, and somehow managed to exceed this quota.
After that the "volume used" and "volume available" goes into negative number , but continued to write without problem.

<a href = http://www.zupimages.net/up/15/22/2z2c.png > I expected to stop when reaching the 100% </a>
<a href = http://www.zupimages.net/up/15/22/z1zp.png> It continued to write </a>

This is also weird for the <code>soft quota</code>, it was fixed at 1TB but in the <code>export</code> file it didn't display any exceed quota (maybe cause the number are now negatives )

<pre><code>
export: 2
volume: 2
root: /rozofs2
squota: 131072000
hquota: 262144000
bsize: 8192
blocks: 27635382
bfree: 18446744073642028726
files: 726
ffree: 52249570
squota_exceed: 0
</code></pre>

the code of the export conf, the vid concerned is the vid 2
<code><pre>
layout = 0;
volumes = (
        {
                vid = 1;
                cids = (
                        {
                                cid = 1;
                                sids = (
                                        {
                                                sid = 1;
                                                host = "era1";
                                        },
                                        {
                                                sid = 2;
                                                host = "era2";
                                        },
                                        {
                                                sid = 3;
                                                host = "era3";
                                        },
                                        {
                                                sid = 4;
                                                host = "era4";
                                        },
                                        {
                                                sid = 5;
                                                host = "era5";
                                        } );
                        },
                        {
                                cid=4;
                                sids= (
                                        {
                                                sid = 1;
                                                host = "era2";
                                        },
                                        {
                                                sid = 2;
                                                host = "era2";
                                        },
                                        {
                                                sid = 3;
                                                host = "era2";
                                        },
                                        {
                                                sid = 4;
                                                host = "era2";
                                        }
                                );

```
                    }
            );
    },
```

{
                vid = 2;
                cids = (
                        {
                                cid = 5;
                                sids = (
                                        {
                                                sid = 1;
                                                host = "era2";
                                        },
                                        {
                                                sid = 2;
                                                host = "era2";
                                        },
                                        {
                                                sid = 3;
                                                host = "era2";
                                        },
                                        {
                                                sid = 4;
                                                host = "era2";

```
                                    },
                                    {
                                            sid = 5;
                                            host = "era2";
                                    },
                                    {
                                            sid = 6;
                                            host = "era2";
                                    },
                                    {
                                            sid = 7;
                                            host = "era2";
                                    },
                                    {
                                            sid = 8;
                                            host = "era2";
                                    },
                                    {
                                            sid = 9;
                                            host = "era1";
                                    },
                                    {
                                            sid = 10;
                                            host = "era1";
                                    },
                                    {
                                            sid = 11;
                                            host = "era1";
                                    }
                            );
                    }
            );
    }
     );
```

exports = (
        {
                eid = 1;
                vid = 1;
                root = "/rozofs";
                md5 = "";
                squota = "40G";
                hquota = "50G";
        },
        {
                eid = 2;
                vid = 2;
                root = "/rozofs2";
                md5 = "";
                squota = "1000G";
                hquota = "2000G";
        }
);
</code></pre>

edit:
I tried to reproduce the same error with a 10G system...instead i got an other one.

<pre><code> era1:~ # df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda3       52402180 15148292  37253888  29% /
devtmpfs        16497688        0  16497688   0% /dev
tmpfs           16504716        0  16504716   0% /dev/shm
tmpfs           16504716     2140  16502576   1% /run
tmpfs           16504716        0  16504716   0% /sys/fs/cgroup
/dev/sda2        1003340    58260    876064   7% /boot
/dev/sda4       83971012 31113220  52857792  38% /export/home
/dev/sdb2      702136356    40716 702095640   1% /rozofs/rozofs1-2
/dev/sdb1      614100000  1125580 612974420   1% /var/lib/ceph/osd/ceph-1
rozofs          10485760 10240000    245760  98% /mnt/rozofs
</code></pre>

let's add a 1 G file

<pre><code> cp /lourd /mnt/rozofs/lourd9</code></pre>

now when i try to exceed the limit, at first it seem it has been prevented

<pre><code>
era1:~ # df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda3       52402180 15156484  37245696  29% /
devtmpfs        16497688        0  16497688   0% /dev
tmpfs           16504716        0  16504716   0% /dev/shm
tmpfs           16504716     2140  16502576   1% /run
tmpfs           16504716        0  16504716   0% /sys/fs/cgroup
/dev/sda2        1003340    58260    876064   7% /boot
/dev/sda4       83971012 31113220  52857792  38% /export/home
/dev/sdb2      702136356    40716 702095640   1% /rozofs/rozofs1-2
/dev/sdb1      614100000  1125580 612974420   1% /var/lib/ceph/osd/ceph-1
rozofs          10485760 10240000    245760  98% /mnt/rozofs
</code></pre>

no changes

but.... the file exist on thesystem

<pre><code>
era1:~ # ls /mnt/rozofs
lourd1  lourd2  lourd3  lourd4  lourd5  lourd6  lourd7  lourd8  lourd9
</code></pre>

and if we look at the 3 storaged where the files are saved

<pre><code>
era4:~ # du -sh /rozofs
5,5G    /rozofs
</code></pre>

<pre><code>
era2:~ # du -sh /rozofs
5,5G    /rozofs
</code></pre>

<pre><code>
era3:~ # du -sh /rozofs
5,5G    /rozofs
</code></pre>

=16,5 G ->  11G*1,5 of data  , the file is correctly saved in the system.

note: also when deleting a file who has been created this way, the system size didn't move neither, but it do if I delete a file who've been created on normal conditions

**Comment by rozonicotine** [comment]
Obsolete
